version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    environment:
      DATABASE_URL: postgresql://${USER}:${PASSWORD}@${HOST}:${PORT}/${DATABASE_NAME} # 환경 변수 사용
    env_file:
      - .env # .env 파일 로드

  frontend:
    build: ./frontend
    container_name: flutter_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    ports:
      - "${PORT}:5432" # 환경 변수 사용
    env_file:
      - .env # .env 파일 로드
    volumes:
      - postgres_data:/var/lib/postgresql/data # 호스트:컨테이너

volumes:
  postgres_data:
