services:
  backend:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${HOST}:${PORT}/${DATABASE_NAME} # 환경 변수 사용
    env_file:
      - .env # .env 파일 로드

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    ports:
      - "${PORT}:5432" # 환경 변수 사용
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - .env # .env 파일 로드
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
volumes:
  postgres_data:










